


import 'package:flutter/animation.dart';

class control
{

  static Color color=Color(0xFF12194A);

  static List titel_image=[
    'image/disney.jpg',
    'image/nature1.jpg',
    'image/animals.jpg',
    'image/galaxy.jpg',
    'image/black.jpg',
    'image/flower.jpg',
    'image/girly.jpg',
    'image/minimal.jpg',
  ];
  static List tile_name=[
    'Disney',
    'Nature',
    'Animals',
    'galaxy',
    'black',
    'flower',
    'girly',
    'minimal',

  ];
  static List disney=[
    'image/disney1.jpg',
    'image/disney3.jpeg',
    'image/disney4.jpg',
    'image/disney5.jpg',
    'image/disney6.jpeg',
    'image/disney7.webp',
    'image/disney8.jpg',
    'image/disney10.jpg',
    'image/disney11.jpg',
    'image/disney12.webp',
    'image/disney13.jpg',
    'image/disney14.jpg',
    'image/disney15.jpg',
    'image/disney16.jpg',
    'image/disney17.jpg',
    'image/disney18.jpg',
    'image/disney19.jpg',
    'image/disney20.jpg',
    'image/disney21.jpg',
    'image/disney22.jpg',
    'image/disney23.jpg',
  ];
  static List Nature=[
    'image/nature1.jpg',
    'image/nature2.jpg',
    'image/nature3.jpg',
    'image/nature4.jpg',
    'image/nature5.jpg',
    'image/nature6.jpg',
    'image/nature7.jpg',
    'image/nature8.jpg',
    'image/nature9.jpg',
    'image/nature10.jpg',
    'image/nature11.jpg',
    'image/nature12.jpg',
    'image/nature13.jpg',
    'image/nature14.jpg',
    'image/nature15.jpg',
    'image/nature16.jpg',
    'image/nature17.jpg',
    'image/nature18.jpg',
    'image/nature19.jpg',
    'image/nature20.jpg',
  ];
  static List Animals=[
    'image/animals.jpg',
    'image/animals1.jpg',
    'image/animals2.jpg',
    'image/animals3.jpg',
    'image/animals4.jpg',
    'image/animals5.jpg',
    'image/animals6.jpg',
    'image/animals7.jpg',
    'image/animals8.jpg',
    'image/animals9.jpg',
    'image/animals10.jpg',
    'image/animals11.jpg',
    'image/animals12.jpg',
    'image/animals13.jpg',
    'image/animals14.jpg',

  ];
  static List galaxy=[
    'image/galaxy1.jpg',
    'image/galaxy2.jpg',
    'image/galaxy3.jpg',
    'image/galaxy4.jpg',
    'image/galaxy5.jpg',
    'image/galaxy6.jpg',
    'image/galaxy7.jpg',
    'image/galaxy8.jpg',
    'image/galaxy9.jpg',
    'image/galaxy10.jpg',
    'image/galaxy11.jpg',
    'image/galaxy12.jpg',
    'image/galaxy13.jpg',
    'image/galaxy14.jpg',
    'image/galaxy15.jpg',
    'image/galaxy16.jpg',
    'image/galaxy17.jpg',
    'image/galaxy18.jpg',
    'image/galaxy19.jpg',


  ];
  static List black=[
    'image/black.jpg',
    'image/black1.jpg',
    'image/black2.jpg',
    'image/black3.jpg',
    'image/black4.jpg',
    'image/black5.jpg',
    'image/black6.jpg',
    'image/black7.jpg',
    'image/black8.jpg',
    'image/black9.jpg',
    'image/black10.jpg',
    'image/black11.jpg',
    'image/black12.jpg',
    'image/black13.jpg',
    'image/black14.jpg',
    'image/black15.jpg',
    'image/black16.jpg',
    'image/black17.jpg',
    'image/black18.jpg',
    'image/black19.jpg',

  ];
  static List flower=[
    'image/flower.jpg',
    'image/flower1.jpg',
    'image/flower2.jpg',
    'image/flower3.jpg',
    'image/flower4.jpg',
    'image/flower5.jpg',
    'image/flower6.jpg',
    'image/flower7.jpg',
    'image/flower8.jpg',
    'image/flower9.jpg',
    'image/flower10.jpg',
    'image/flower11.jpg',
    'image/flower12.jpg',
    'image/flower13.jpg',
    'image/flower14.jpg',
    'image/flower15.jpg',
    'image/flower16.jpg',
    'image/flower17.jpg',
    'image/flower18.jpg',
    'image/flower19.jpg',
    'image/flower20.jpg',
    'image/flower21.jpg',
    'image/flower22.jpg',
    'image/flower23.jpg',
    'image/flower24.jpg',
    'image/flower25.jpg',
    'image/flower26.jpg',
    'image/flower27.jpg',
    'image/flower28.jpg',
    'image/flower29.jpg',

  ];
  static List girly=[
    'image/girly.jpg',
    'image/girly1.jpg',
    'image/girly2.jpg',
    'image/girly3.jpg',
    'image/girly4.jpg',
    'image/girly5.jpg',
    'image/girly6.jpg',
    'image/girly7.jpg',
    'image/girly8.jpg',
    'image/girly9.jpg',
    'image/girly10.jpg',

  ];
  static List minimal=[
    'image/minimal.jpg',
    'image/minimal1.jpg',
    'image/minimal2.jpg',
    'image/minimal3.jpg',
    'image/minimal4.jpg',
    'image/minimal5.jpg',
    'image/minimal6.jpg',
    'image/minimal7.jpg',
    'image/minimal8.jpg',
    'image/minimal9.jpg',
    'image/minimal10.jpg',
    'image/minimal11.jpg',
    'image/minimal12.jpg',
    'image/minimal13.jpg',
    'image/minimal14.jpg',
    'image/minimal15.jpg',
    'image/minimal16.jpg',
    'image/minimal17.jpg',
    'image/minimal18.jpg',

  ];

}